### ISSUE TITLE
When can we view the eval.ai results?

### ISSUE THREAD

**Issue by 82magnolia** [saimwani/multion-challenge#2]
Hello, thanks for hosting a nice challenge.

I made a toy submission to evalai using the commands provided in the README, but cannot view the evaluation results.
All I can see for now is that my submission is 'submitted'.
Does it take a while to receive agent performance statistics? In general, how long does it take?

I have made a submission using the following command (after building the docker image)
`evalai push multi_on:latest --phase multion-dev-805`

Below is the current status of my submission (captured from eval.ai)
![image](https://user-images.githubusercontent.com/31164435/112573731-3b560680-8e30-11eb-80af-791b00ac4aa6.png)

**Comment by saimwani** [comment]
Hi,
The results are updated as soon as your submission has been evaluated. This can vary depending on your agent and the number of submissions in the queue. The toy submission would take almost no time in running because it uses a random agent. I see that some of your submissions had run into exceptions which is why the results were not updated. Make sure you have evaluated your docker submission without errors locally before you submit.

**Comment by 82magnolia** [comment]
It seems like there was a bug in my submission. Thanks!

**Comment by 82magnolia** [comment]
I have made a new test submission, but the result is not appearing, even after 24 hours since the submission. On average, how long does it take for 'submission failure' to be notified? I see that once a valid submission is made, results appear shortly after submission.

**Comment by saimwani** [comment]
It appears there was an issue with EvalAI. Your submission results have now been updated.

**Comment by 82magnolia** [comment]
Thanks!
